baseURL = "https://iainazeem.github.io/"
languageCode = "en-us"
title = "Ain Azeem | Full Stack Developer"
theme = ""

[params]
  name = "Ain Azeem"
  description = "Full Stack Developer"
  github = "iAinAzeem"
