baseURL = "https://iainazeem.github.io/iainazeem/"
languageCode = "en-us"
title = "Ain Azeem | Full Stack Developer"
paginate = 10

[params]
  name = "Ain Azeem"
  description = "Full Stack Developer"
  github = "iAinAzeem"
